name: storymode
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    # Core dependencies
    - pydantic>=2.7
    - jsonschema>=4.22
    - tqdm>=4.66
    - python-dotenv>=1.0
    - typer>=0.12
    - rich>=13.7
    - orjson>=3.10
    - regex>=2024.4.28
    - numpy>=1.26
    - pandas>=2.2
    - scikit-learn>=1.5
    - httpx>=0.27
    - tenacity>=8.3
    
    # PyTorch and ML dependencies (install first)
    - torch>=2.0.0
    - torchvision
    - torchaudio
    
    # Additional dependencies for model compatibility
    - safetensors>=0.3.0
    - tokenizers>=0.13.0
    - huggingface-hub>=0.16.0
    - einops>=0.6.0
    - protobuf>=3.20.0
    - sentencepiece>=0.1.99
    
    # Transformers and model inference (install last)
    - transformers>=4.35.0
    - accelerate>=0.20.0
    - vllm>=0.2.0
    
    # Optional: for better performance
    - ninja
    - packaging
